In [1]:
import pandas as pd

In [73]:
df = pd.read_csv("12345.csv")

In [74]:
df[df.group==1].sample(20)

,Unnamed: 0,zone,province,type,2545,2547,2549,2550,2552,2554,2556,2558,2560,group
266,266,ภาคเหนือ,ตาก,หนี้สินทั้งสิ้น,34293.41,77658.11,80859,62642,77591,60389.5,120246.1,145791.2,127988.45,1
462,462,ภาคใต้,ภูเก็ต,หนี้สินทั้งสิ้น,135781.71,71470.88,72379,82362,80201,71828.9,91903.8,135375.9,239551.96,1
26,26,ภาคกลาง,ปทุมธานี,เพื่อใช้ซื้อ/เช่าซื้อบ้านและที่ดิน,0.00,82034.13,97834,66390,132028,46111.5,257560.0,110837.8,179751.17,1
119,119,ภาคกลาง,สระแก้ว,หนี้สินทั้งสิ้น,69543.05,64943.26,88116,101281,105886,106147.1,166090.3,249126.9,169875.58,1
483,483,ภาคใต้,ชุมพร,หนี้สินทั้งสิ้น,87802.28,90195.02,116327,127313,124643,130163.6,197458.5,199745.9,157728.32,1
28,28,ภาคกลาง,พระนครศรีอยุธยา,หนี้สินทั้งสิ้น,26106.92,49446.03,53222,54762,163425,81609.4,106260.1,216815.6,234446.06,1
399,399,ภาคตะวันออกเฉียงเหนือ,มหาสารคาม,หนี้สินทั้งสิ้น,67865.64,85820.47,109654,90740,177380,167718.0,194195.1,128257.6,248623.18,1
147,147,ภาคกลาง,นครปฐม,หนี้สินทั้งสิ้น,124110.63,174832.09,167798,100110,101030,59484.4,175893.9,153504.0,75904.34,1
133,133,ภาคกลาง,กาญจนบุรี,หนี้สินทั้งสิ้น,86943.13,62815.80,114158,91113,107527,68785.6,105780.2,89861.9,157164.45,1
175,175,ภาคกลาง,ประจวบคีรีขันธ์,หนี้สินทั้งสิ้น,57042.19,79518.95,128589,140536,173821,159828.4,222218.9,168373.8,160756.74,1
413,413,ภาคตะวันออกเฉียงเหนือ,กาฬสินธุ์,หนี้สินทั้งสิ้น,73431.56,65455.58,109921,144115,97711,154871.2,124724.5,131577.2,134001.77,1
154,154,ภาคกลาง,สมุทรสาคร,หนี้สินทั้งสิ้น,131560.68,64616.07,138320,69569,133793,104821.6,56367.4,128830.4,104677.28,1
511,511,ภาคใต้,พัทลุง,หนี้สินทั้งสิ้น,80866.80,89967.46,117631,129637,140417,169818.7,162248.7,206986.4,183717.82,1
84,84,ภาคกลาง,จันทบุรี,หนี้สินทั้งสิ้น,145209.49,184233.23,176403,186301,125646,124265.5,110504.3,130258.2,186071.96,1
497,497,ภาคใต้,สตูล,หนี้สินทั้งสิ้น,56518.37,82045.70,69314,116896,183123,101355.4,155314.4,145458.0,166360.94,1
287,287,ภาคเหนือ,พิจิตร,หนี้สินทั้งสิ้น,97142.10,119655.77,104379,143162,138861,161004.5,208219.2,148750.8,176992.30,1
322,322,ภาคตะวันออกเฉียงเหนือ,ศรีสะเกษ,หนี้สินทั้งสิ้น,60652.18,71816.26,95247,99032,88342,112525.5,191056.9,135277.4,189527.94,1
427,427,ภาคตะวันออกเฉียงเหนือ,นครพนม,หนี้สินทั้งสิ้น,121363.18,85536.78,85741,70049,92430,76337.8,90411.0,102816.0,192867.55,1
385,385,ภาคตะวันออกเฉียงเหนือ,เลย,หนี้สินทั้งสิ้น,48795.75,79127.16,118555,108560,96423,123951.1,103669.9,169523.4,148123.99,1
350,350,ภาคตะวันออกเฉียงเหนือ,อำนาจเจริญ,หนี้สินทั้งสิ้น,49225.48,112722.49,96400,109063,159633,145074.3,134560.1,173275.8,226032.61,1

In [61]:
count = 0
for i in df.index:
    num = i - count
    if df.iloc[num]['type'] == 'หนี้สินทั้งสิ้น':
        df = df.drop([i])
        count += 1

In [46]:
df.sample(10)

,Unnamed: 0,zone,province,type,2545,2547,2549,2550,2552,2554,2556,2558,2560,group
491,491,ภาคใต้,สงขลา,เพื่อใช้จ่ายในครัวเรือน,71413.10,33412.39,37676,50069,46442,47323.9,65756.6,77191.9,70104.24,2
436,436,ภาคตะวันออกเฉียงเหนือ,มุกดาหาร,เพื่อใช้ทำธุรกิจที่ไม่ใช่การเกษตร,9473.55,26384.48,7206,8467,16462,11991.0,20619.1,42348.4,8758.29,0
325,325,ภาคตะวันออกเฉียงเหนือ,ศรีสะเกษ,เพื่อใช้ทำการเกษตร,14352.80,14327.87,17171,23891,34818,30698.1,33009.3,30965.2,41780.32,0
276,276,ภาคเหนือ,สุโขทัย,เพื่อใช้ทำการเกษตร,18025.93,19665.10,25518,34169,28111,53569.0,39776.3,85392.6,70387.89,2
351,351,ภาคตะวันออกเฉียงเหนือ,อำนาจเจริญ,เพื่อใช้จ่ายในครัวเรือน,26315.76,49615.15,39164,48083,65138,78256.3,57589.7,63775.3,89495.54,2
135,135,ภาคกลาง,กาญจนบุรี,เพื่อใช้ทำธุรกิจที่ไม่ใช่การเกษตร,12780.83,7348.99,18339,15280,7384,3849.4,12098.9,12389.5,14566.22,3
207,207,ภาคเหนือ,อุตรดิตถ์,เพื่อใช้ในการศึกษา,0.00,0.00,3943,4723,3497,1895.8,641.4,1589.9,4348.19,3
309,309,ภาคตะวันออกเฉียงเหนือ,บุรีรัมย์,เพื่อใช้จ่ายในครัวเรือน,37827.56,42994.48,46073,48033,46845,75833.5,62672.4,69193.1,71607.34,2
523,523,ภาคใต้,ปัตตานี,เพื่อใช้ซื้อ/เช่าซื้อบ้านและที่ดิน,0.00,18809.28,35896,31553,20758,23060.2,29669.6,40289.5,28988.50,0
67,67,ภาคกลาง,สระบุรี,เพื่อใช้ในการศึกษา,0.00,0.00,2153,972,1469,1215.5,1441.4,2296.4,1857.92,3